CREATE TABLE IF NOT EXISTS records (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    temperature VARCHAR(255) NOT NULL,
    distance VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);